services:
  pushgateway:
    image: ${IMAGE_NAME:-prom/pushgateway}:${IMAGE_TAG:-latest}
    command:
      - --web.listen-address=:${PORT}
      - --web.telemetry-path=${METRICS_PATH}
      - --persistence.file=${DATA_PATH}/metrics
      - --persistence.interval=${PERSISTENCE_INTERVAL}
      - --log.level=${LOG_LEVEL}
    networks:
      metric-net:
      traefik-net:
    volumes:
      - data-vol:${DATA_PATH}
    healthcheck:
      test: wget -q -O - http://127.0.0.1:${PORT}/-/healthy
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-15s}
      retries: ${HEALTHCHECK_RETRIES:-5}
      start_period: ${HEALTHCHECK_START_PERIOD:-1m}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.enable: ${TRAEFIK_ENABLE:-true}
        traefik.http.routers.pushgateway.entrypoints: ${TRAEFIK_ENTRYPOINT:-http}
        traefik.http.routers.pushgateway.rule: Host(`${TRAEFIK_SUBDOMAIN:-pushgateway}.${PUBLIC_HOSTNAME}`)
        traefik.http.middlewares.pushgateway-auth.basicauth.users: ${TRAEFIK_AUTH}
        traefik.http.routers.pushgateway.middlewares: pushgateway-auth
        traefik.http.services.pushgateway.loadbalancer.server.port: ${PORT}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-64M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-16M}

networks:
  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    driver: ${METRIC_NET_DRIVER:-overlay}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true
